### PR TITLE
Mingqing: Adding files to convert txt to json

### PR DESCRIPTION
**Pull request by mingqingzhu**

### CODE REVIEW

**Comment by mingqingzhu** [comment]
Screen Shot 2022-09-12 at 12 39 06 PM
Screen Shot 2022-09-12 at 12 39 16 PM

**Comment by AllenNguyen0417** [comment]
Everything looks good

**Comment by jiayue123** [comment]
Everything looks good

**Comment by simrahhussain2323** [comment]
All of it looks great, keep it up!

**Review by varaprasadperambudoori — APPROVED** [review]

**Pull request merged**
