### PR TITLE
init AlexInputText Text file and AlexTxtToJson Java class file

### PR DESCRIPTION
**Pull request by VuongAlexander**

### CODE REVIEW

**Comment by VuongAlexander** [comment]
image

**Comment by swu465** [comment]
Everything looks good.

**Comment by AllenNguyen0417** [comment]
Everything looks good

**Comment by MidoraSolos** [comment]
Looks good to me, Was just wondering if this would work without the curly braces in the input

**Comment by jiayue123** [comment]
Everything looks good

**Comment by mingqingzhu** [comment]
Everything looks good

**Comment by simrahhussain2323** [comment]
Everything looks great, JSON's formatting is exactly how it should be!

**Pull request merged**
