### PR TITLE
Simon wu

### PR DESCRIPTION
**Pull request by swu465**
image

### CODE REVIEW

**Comment by MidoraSolos** [comment]
Looks good to me

**Comment by JCabrera-Nisum** [comment]
JSON file looks good

**Comment by mingqingzhu** [comment]
Everything looks good

**Comment by ElizabethFeng** [comment]
Awesome code! Input TXT file is able to convert to JSON file. BufferedReader was something I did not use, but your implementation provides a great example.

**Comment by simrahhussain2323** [comment]
Everything is great structure format and all!

**Pull request merged**
