### PR TITLE
jiayue:Adding file to convert txt to json

### PR DESCRIPTION
**Pull request by jiayue123**

### CODE REVIEW

**Comment by jiayue123** [comment]
Screen Shot 2022-09-12 at 1 49 02 PM
-images.githubusercontent.com/58449266/189756046-c653d288-04b3-4569-b2b0-ec892a620f60.png">

**Comment by jiayue123** [comment]
Screen Shot 2022-09-12 at 1 49 02 PM
input

**Comment by jiayue123** [comment]
Screen Shot 2022-09-12 at 1 49 49 PM
output

**Comment by ElizabethFeng** [comment]
The creation of your own JSON data is very unique and also the use of arrays to organize the output. The implementation looks awesome!

**Pull request merged**
