### PR TITLE
joshua: add java and txt file

### PR DESCRIPTION
**Pull request by JCabrera-Nisum**
image

### CODE REVIEW

**Comment by swu465** [comment]
Looks good. Just need to rename the java file you added to include your name.

**Comment by JCabrera-Nisum** [comment]
image
my output

**Comment by mingqingzhu** [comment]
Looks good, but I am not sure if the format matters as usually json data does not stay in one line.

**Comment by JCabrera-Nisum** [comment]
> Looks good. Just need to rename the java file you added to include your name.

thanks. I updated the name of the file

**Comment by ElizabethFeng** [comment]
Code for the conversion of JSON file from TXT file is very concise. I also had an output similar to yours but as Mingqing mentioned I am also unsure if this is an acceptable output for JSON data.

**Comment by simrahhussain2323** [comment]
Looks good, might want to double check on JSON output as mentioned above. I believe I might be in a similar scenario as well. 

Great job though!

**Comment by ZMohamedy** [comment]
JSON format might need to be on three lines. Looks good otherwise

**Pull request merged**
